// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBj3sTJsIdqqBv73JjC2lX1gCCLvXT4LVc',
    appId: '1:364155476442:web:10af0a7508be3ea201c8e3',
    messagingSenderId: '364155476442',
    projectId: 'readhub-18dbe',
    authDomain: 'readhub-18dbe.firebaseapp.com',
    storageBucket: 'readhub-18dbe.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA38r6Vin4TQxrggNWOKqyIROsCOehycqg',
    appId: '1:364155476442:android:6bb769db109ed6a501c8e3',
    messagingSenderId: '364155476442',
    projectId: 'readhub-18dbe',
    storageBucket: 'readhub-18dbe.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAwYpzf75DXvMf0WcCe_ObMPuNG5aDVFfc',
    appId: '1:364155476442:ios:cc190363855a9dab01c8e3',
    messagingSenderId: '364155476442',
    projectId: 'readhub-18dbe',
    storageBucket: 'readhub-18dbe.firebasestorage.app',
    iosBundleId: 'com.example.readhub',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAwYpzf75DXvMf0WcCe_ObMPuNG5aDVFfc',
    appId: '1:364155476442:ios:cc190363855a9dab01c8e3',
    messagingSenderId: '364155476442',
    projectId: 'readhub-18dbe',
    storageBucket: 'readhub-18dbe.firebasestorage.app',
    iosBundleId: 'com.example.readhub',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBj3sTJsIdqqBv73JjC2lX1gCCLvXT4LVc',
    appId: '1:364155476442:web:9fafeaca0b6ff6c501c8e3',
    messagingSenderId: '364155476442',
    projectId: 'readhub-18dbe',
    authDomain: 'readhub-18dbe.firebaseapp.com',
    storageBucket: 'readhub-18dbe.firebasestorage.app',
  );
}
