// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCu9zfw-AC7VZaa5SOJnI9KTW9MqzZfomc',
    appId: '1:1092299868449:web:0eea3feccc6b37c4229660',
    messagingSenderId: '1092299868449',
    projectId: 'mini-duyuru',
    authDomain: 'mini-duyuru.firebaseapp.com',
    storageBucket: 'mini-duyuru.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD4VJg80XdYrqX8lYaS4CIZsZna_9f-_mw',
    appId: '1:1092299868449:android:17bac0e6d149ac13229660',
    messagingSenderId: '1092299868449',
    projectId: 'mini-duyuru',
    storageBucket: 'mini-duyuru.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDOb_kc3UZuLPreRQtf8Et_xuXQNddPUR8',
    appId: '1:1092299868449:ios:3f9e8f5252c15887229660',
    messagingSenderId: '1092299868449',
    projectId: 'mini-duyuru',
    storageBucket: 'mini-duyuru.firebasestorage.app',
    iosBundleId: 'com.example.miniduyuru',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDOb_kc3UZuLPreRQtf8Et_xuXQNddPUR8',
    appId: '1:1092299868449:ios:3f9e8f5252c15887229660',
    messagingSenderId: '1092299868449',
    projectId: 'mini-duyuru',
    storageBucket: 'mini-duyuru.firebasestorage.app',
    iosBundleId: 'com.example.miniduyuru',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCu9zfw-AC7VZaa5SOJnI9KTW9MqzZfomc',
    appId: '1:1092299868449:web:5dc6794271ba7bbf229660',
    messagingSenderId: '1092299868449',
    projectId: 'mini-duyuru',
    authDomain: 'mini-duyuru.firebaseapp.com',
    storageBucket: 'mini-duyuru.firebasestorage.app',
  );
}
